### PR TITLE
Issue 5 translate countries to Spanish Language

### LINKED ISSUE #5: Translate countries
**Is your feature request related to a problem? Please describe.**
Right now the countries are still in English.

**Describe the solution you'd like**
A countries.php with the translations of the countries.

**TODO**
- [X] English
- [X] Dutch - @jatempa & @sebastiaanspeck 
- [X] Spanish - @jatempa
- [X] German - @sandroacoelho
- [X] Brazilian Portuguese - @guastallaigor 
- [X] French - @davidmohamedfr
- [x] Italian - @FedeX15 
- [x] Indonesian - @nipeharefa

### PR DESCRIPTION
**Pull request by jatempa**
# Pull Request #5 

Create a "countries.php" file to 'en', 'es', 'nl' folder

### Please tell us , the type of Change you are submiting:
Select one of the following: 

- [ ] Bug
- [X] Feature
- [ ] Minor Change

### Does it fix an existing issue? Please tell us which one
    Resolves #5 

### Description of what's been changed

I have translated countries to Spanish Language

### CODE REVIEW

**Comment by sebastiaanspeck** [comment]
Thats not what I meant with `'country' => 'country'`. I wanted the full list of countries in it, so:
```
'Argentina'                     => 'Argentina',
'Australia'                     => 'Australia',
'Austria'                       => 'Austria',
```
etc.

**Comment by sebastiaanspeck** [comment]
There are still some countries not translated in the countries.php in es... I can't imagine that the Spanish language doesn't have translations for them.

**Comment by jatempa** [comment]
Some countries names are the Same in Spanish and English language

**Comment by sebastiaanspeck** [comment]
> Some countries names are the Same in Spanish and English language

Ah okay. Lazy Spanish :laugh:

**Comment by sebastiaanspeck** [comment]
> Of course !

Thanks!

**Comment by jatempa** [comment]
Pleas @sebastiaanspeck can you check my changes?

**Comment by sebastiaanspeck** [comment]
> Please @sebastiaanspeck can you check my changes?

Looking good! Thansk, I will merge it.

**Pull request merged**
