### PR TITLE
Fix top scorers for excluded leagues

### LINKED ISSUE #36: Fix top scorers for excluded leagues
**Is your feature request related to a problem? Please describe.**
Right now the top scorers are not shown for World Cup. 
At this moment this is no issue for Champions League and Europa League, but this will become an issue when those tournaments reach knock-out phase

**Describe the solution you'd like**
Show the top scorers for the World Cup (not only the final but the whole tournament)

**Additional context**
I think we need to use aggregated endpoint here:
`$soccerAPI->topscorers()->setInclude($includeTopscorersAggregated)->aggregatedBySeasonId($league->current_season_id)->aggregatedGoalscorers->data;`

### PR DESCRIPTION
**Pull request by Visovsiouk**
# Pull Request [Fix top scorers for excluded leagues]

Added `CustomSoccerApi` that extends `SoccerApi` from the `kirill-latish` package. The new class calls to  `CustomTopScorer` request in which I have added the `aggregatedBySeasonId()` method which does not exist in the original package.

- [ ] Bug
- [X] Feature
- [ ] Minor Change

### Does it fix an existing issue? Please tell us which one

Resolves #36

### CODE REVIEW

**Comment by sebastiaanspeck** [comment]
Have you tested it with multiple leagues? I think it will also use the topscorersAggregated for other leagues that are not having this issue

**Comment by Visovsiouk** [comment]
@sebastiaanspeck What should be the desired result to test?

**Comment by sebastiaanspeck** [comment]
Well, right now the top scorers are not shown for World Cup.
At this moment this is no issue for Champions League and Europa League, but this will become an issue when those tournaments reach knock-out phase.

These leagues need to use this aggregated but I don't want to put these league-ids hardcoded so you got to find a way to seperate these leagues from the leagues who don't need the aggregated

**Comment by sebastiaanspeck** [comment]
test your code with the next leagues:
- Pro League -> these one doesn't show any top scorers because of 
  ```                 
  if(count($topscorersAggregated) > 0) {
      $topscorers = $topscorersAggregated;
  } else {
      $topscorers = array();
  }
  ```

  instead it needs to use the $topscorersDefault and only request the topscorersAggregated if the league is World Cup, Champions League and Europa League.

- Premier League -> this one also uses the $topscorersAggregated, which is incorrect, but it also 
   shows all 123 topscorers. I want a top 10.

- FA Cup (or any other cup) -> this one doesn't need to show any top scorers
- World Cup -> show the aggregated top scorers
- Champions League/Europa League -> show the aggregated top scorers, but leave out the top scorers from the qualifications-rounds

**Comment by sebastiaanspeck** [comment]
Use the current master-branch as starting point.

I have a folder soccerapi in the root. If you copy the contents of it to vendor/kirill-latish, you can use 

```
$soccerAPI->topscorers()->setInclude($includeTopscorersAggregated)->aggregatedBySeasonId($league->current_season_id)->aggregatedGoalscorers->data;
```

**Comment by sebastiaanspeck** [comment]
You can get all possible stages for the league. View the docs for the league-endpoint and you can exclude the stages we don’t want using the stage-ids

**Pull request merged**
