### PR TITLE
add bahasa language

### PR DESCRIPTION
**Pull request by nipeharefa**
Add **Bahasa Indonesia** translation

### CODE REVIEW

**Comment by sebastiaanspeck** [comment]
Not all strings are translated. If thats okay with you, I can merge it.

**Comment by nipeharefa** [comment]
@sebastiaanspeck Okay, i will improve the translation after your merge it.
Some of validation message has been provide in https://github.com/caouecs/Laravel-lang.

**Comment by sebastiaanspeck** [comment]
I don’t use those built-in language-files right now in the application. I meant the application.php. I will merge it, but please translate the other strings soon.

**Comment by sebastiaanspeck** [comment]
After the merge, I found out that you changed the validation.php from NL. I fixed it.

**Pull request merged**
